FROM httpd:2

MAINTAINER Martin Etmajer <martin.etmajer@dynatrace.com>

ENV APACHE_CONF_PATH "/usr/local/apache2/conf/httpd.conf"

ENV DT_WSAGENT_NAME           "apache-wsagent"
ENV DT_WSAGENT_COLLECTOR_HOST "dtcollector"
ENV DT_WSAGENT_COLLECTOR_PORT "9998"
ENV DT_WSAGENT_PATH           "/opt/dynatrace/agent/lib64/libdtagent.so"

ENV ANSIBLE_DEPS "python python-dev python-pip"
ENV ANSIBLE_ROLE "Dynatrace-Apache-HTTPServer-Agent"

RUN echo "---\n\
- hosts: all\n\
  roles:\n\
  - role: dynatrace.${ANSIBLE_ROLE}\n\
    dynatrace_apache_agent_linux_agent_path:             ${DT_WSAGENT_PATH}\n\
    dynatrace_apache_agent_linux_apache_config_path:     ${APACHE_CONF_PATH}\n\
    dynatrace_apache_agent_do_patch_apache_initd_script: no\n\
    dynatrace_apache_agent_name:                         ${DT_WSAGENT_NAME}\n\
    dynatrace_wsagent_collector_hostname:                ${DT_WSAGENT_COLLECTOR_HOST}\n\
    dynatrace_wsagent_collector_port:                    ${DT_WSAGENT_COLLECTOR_PORT}\n\
    dynatrace_wsagent_linux_installer_file_url:          http://10.0.2.2/dynatrace/dynatrace-wsagent.tar"\
> /tmp/ansible-playbook.yml

RUN apt-get update && \
    apt-get install -y sudo ${ANSIBLE_DEPS} && \
    pip install ansible && \
    ansible-galaxy install dynatrace.${ANSIBLE_ROLE} -p /tmp/roles && \
    ansible-playbook -i localhost, -c local /tmp/ansible-playbook.yml && \
    pip uninstall -y ansible && \
    apt-get remove --purge -y ${ANSIBLE_DEPS} && \
    rm -rf /var/lib/apt/lists/* /tmp/*

CMD ["sh", "-c", "/etc/init.d/dynaTraceWebServerAgent start && httpd-foreground"]
