FROM alpine:3.3

MAINTAINER Martin Etmajer <martin.etmajer@dynatrace.com>

ENV VERSION             "6.3"
ENV INSTALLER_FILE_NAME "dynatrace-server-linux-x86.jar"
ENV INSTALLER_URL       "http://downloads.dynatracesaas.com/${VERSION}/${INSTALLER_FILE_NAME}"

ENV DT                  "/dynatrace"
ENV COLLECTOR_PORT      "6698"
ENV COLLECTOR_PORT_SSL  "6699"

ENV  DT_INSTALL_DEPS "openjdk8-jre-base"
ENV  DT_RUNTIME_DEPS "bash curl"
RUN  apk add --no-cache ${DT_INSTALL_DEPS} ${DT_RUNTIME_DEPS} && \
     curl -L -o /tmp/${INSTALLER_FILE_NAME} ${INSTALLER_URL} && \
     java -jar /tmp/${INSTALLER_FILE_NAME} -b 64 -t ${DT} -y && \
     apk del ${DT_INSTALL_DEPS} && \
     rm -rf /tmp/*
RUN  sed -i '/^-memory/,/^unsupported/c\-memory\ndemo' ${DT}/dtserver.ini && \
     sed -i '/^-memory/,/^unsupported/c\-memory\ndemo' ${DT}/dtfrontendserver.ini && \
     echo '-Dcom.dynatrace.diagnostics.filestore.numStorageThreads=1' >> ${DT}/dtserver.ini 
COPY build/config/server.config.xml ${DT}/server/conf

ENV  GLIBC_RUNTIME_DEPS "libgcc"
COPY build/bin/glibc-2.21-r2.apk /tmp
COPY build/bin/glibc-bin-2.21-r2.apk /tmp
RUN  apk add --no-cache ${GLIBC_RUNTIME_DEPS} && \
     apk add --allow-untrusted /tmp/glibc-2.21-r2.apk && \
     apk add --allow-untrusted /tmp/glibc-bin-2.21-r2.apk && \
     /usr/glibc/usr/bin/ldconfig /lib /usr/glibc/usr/lib && \
     rm -rf /tmp/*

# Make sure that hostname resolution looks up /etc/hosts prior to /etc/resolv.conf
RUN echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf

COPY build/scripts/pull-license-key-file.sh /
COPY build/scripts/run-process.sh /

# Dynatrace Clients (TCP)
EXPOSE 2020
# Dynatrace Clients (TCP with SSL)
EXPOSE 2021
# Dynatrace Collectors (TCP)
EXPOSE 6698
# Dynatrace Collectors (TCP with SSL)
EXPOSE 6699
# Dynatrace Web Server (HTTP)
EXPOSE 8020
# Dynatrace Web Server (HTTPS)
EXPOSE 8021
# Dynatrace Web UI (HTTPS)
EXPOSE 9911
# Dynatrace Agents (TCP)
EXPOSE 9998

CMD /pull-license-key-file.sh ; /run-process.sh