FROM alpine:3.3

MAINTAINER Martin Etmajer <martin.etmajer@dynatrace.com>

ENV VERSION             "6.3"
ENV INSTALLER_FILE_NAME "dynatrace-collector-linux-x86.jar"
ENV INSTALLER_URL       "http://downloads.dynatracesaas.com/${VERSION}/${INSTALLER_FILE_NAME}"

ENV DT                  "/dynatrace"
ENV AGENT_PORT          "9998"

ENV  DT_INSTALL_DEPS "curl openjdk8-jre-base"
ENV  DT_RUNTIME_DEPS "bash"
RUN  apk add --no-cache ${DT_INSTALL_DEPS} ${DT_RUNTIME_DEPS} && \
     curl -L -o /tmp/${INSTALLER_FILE_NAME} ${INSTALLER_URL} && \
     java -jar /tmp/${INSTALLER_FILE_NAME} -b 64 -t ${DT} -y && \
     apk del ${DT_INSTALL_DEPS} && \
     rm -rf /tmp/*

ENV  GLIBC_RUNTIME_DEPS "libgcc"
COPY build/bin/glibc-2.21-r2.apk /tmp
COPY build/bin/glibc-bin-2.21-r2.apk /tmp
RUN  apk add --no-cache ${GLIBC_RUNTIME_DEPS} && \
     apk add --allow-untrusted /tmp/glibc-2.21-r2.apk && \
     apk add --allow-untrusted /tmp/glibc-bin-2.21-r2.apk && \
     /usr/glibc/usr/bin/ldconfig /lib /usr/glibc/usr/lib && \
     rm -rf /tmp/*

# Make sure that hostname resolution looks up /etc/hosts prior to /etc/resolv.conf
RUN echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf

ENV  WAIT_FOR_CMD_RUNTIME_DEPS "netcat-openbsd"
COPY build/scripts/wait-for-cmd.sh /usr/local/bin
RUN  apk add --no-cache ${WAIT_FOR_CMD_RUNTIME_DEPS}

COPY build/scripts/run-process.sh /

# Dynatrace Agents (TCP)
EXPOSE 9998

CMD /run-process.sh