FROM nginx

MAINTAINER Martin Etmajer <martin.etmajer@dynatrace.com>

ENV DT_WSAGENT_NAME           "nginx-wsagent"
ENV DT_WSAGENT_COLLECTOR_HOST "dtcollector"
ENV DT_WSAGENT_COLLECTOR_PORT "9998"
ENV DT_WSAGENT_PATH           "/opt/dynatrace/agent/lib64/libdtagent.so"

ENV ANSIBLE_DEPS "python python-dev python-pip"
ENV ANSIBLE_ROLE "Dynatrace-WebServer-Agent"

ENV NGINX_AGENT_DEPS "nginx-dbg gdb elfutils bc"

RUN echo "---\n\
- hosts: all\n\
  roles:\n\
  - role: dynatrace.${ANSIBLE_ROLE}\n\
    dynatrace_wsagent_name:                     ${DT_WSAGENT_NAME}\n\
    dynatrace_wsagent_collector_hostname:       ${DT_WSAGENT_COLLECTOR_HOST}\n\
    dynatrace_wsagent_collector_port:           ${DT_WSAGENT_COLLECTOR_PORT}"\
> /tmp/ansible-playbook.yml

RUN apt-get update && \
    apt-get install -y sudo ${ANSIBLE_DEPS} ${NGINX_AGENT_DEPS} && \
    pip install ansible && \
    ansible-galaxy install dynatrace.${ANSIBLE_ROLE} -p /tmp/roles && \
    ansible-playbook -i localhost, -c local /tmp/ansible-playbook.yml && \
    pip uninstall -y ansible && \
    apt-get remove --purge -y ${ANSIBLE_DEPS} && \
    rm -rf /var/lib/apt/lists/* /tmp/*

CMD ["sh", "-c", "/etc/init.d/dynaTraceWebServerAgent start; LD_PRELOAD=/opt/dynatrace/agent/lib64/libdtagent.so nginx -g 'daemon off;'"]
