FROM glassfish:4.0

MAINTAINER Martin Etmajer <martin.etmajer@dynatrace.com>

ENV DT_GLASSFISH_AGENT_GLASSFISH_DOMAIN_XML_FILE "/usr/local/glassfish4/glassfish/domains/domain1/config/domain.xml"
ENV DT_GLASSFISH_AGENT_NAME                      "glassfish-agent"
ENV DT_GLASSFISH_AGENT_COLLECTOR_HOST            "dtcollector"
ENV DT_GLASSFISH_AGENT_COLLECTOR_PORT            "9998"

ENV ANSIBLE_DEPS "python python-dev python-pip"
ENV ANSIBLE_ROLE "Dynatrace-Glassfish-Agent"

RUN echo "---\n\
- hosts: all\n\
  roles:\n\
  - role: dynatrace.${ANSIBLE_ROLE}\n\
    dynatrace_glassfish_agent_glassfish_domain_xml_file: ${DT_GLASSFISH_AGENT_GLASSFISH_DOMAIN_XML_FILE}\n\
    dynatrace_glassfish_agent_name:                      ${DT_GLASSFISH_AGENT_NAME}\n\
    dynatrace_glassfish_agent_collector_hostname:        ${DT_GLASSFISH_AGENT_COLLECTOR_HOST}\n\
    dynatrace_glassfish_agent_collector_port:            ${DT_GLASSFISH_AGENT_COLLECTOR_PORT}"\
> /tmp/ansible-playbook.yml

RUN apt-get update && \
    apt-get install -y sudo ${ANSIBLE_DEPS} && \
    pip install ansible && \
    ansible-galaxy install dynatrace.${ANSIBLE_ROLE} -p /tmp/roles && \
    ansible-playbook -i localhost, -c local /tmp/ansible-playbook.yml && \
    pip uninstall -y ansible && \
    apt-get remove --purge -y ${ANSIBLE_DEPS} && \
    rm -rf /var/lib/apt/lists/* /tmp/*
